service: rns-server

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  
plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
    timeout: 30
